env:
  browser: true
  es2021: true
  meteor: true
  node: true
extends: 
  - eslint:recommended
parserOptions:
  ecmaVersion: 13
  sourceType: module
  ecmaFeatures:
    jsx: true
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
globals:
  process: true
